set(_CATKIN_CURRENT_PACKAGE "02_RANSAC")
set(02_RANSAC_VERSION "0.0.0")
set(02_RANSAC_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(02_RANSAC_PACKAGE_FORMAT "2")
set(02_RANSAC_BUILD_DEPENDS "pcl" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(02_RANSAC_BUILD_EXPORT_DEPENDS "pcl" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(02_RANSAC_BUILDTOOL_DEPENDS "catkin")
set(02_RANSAC_BUILDTOOL_EXPORT_DEPENDS )
set(02_RANSAC_EXEC_DEPENDS "pcl" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(02_RANSAC_RUN_DEPENDS "pcl" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(02_RANSAC_TEST_DEPENDS )
set(02_RANSAC_DOC_DEPENDS )
set(02_RANSAC_URL_WEBSITE "")
set(02_RANSAC_URL_BUGTRACKER "")
set(02_RANSAC_URL_REPOSITORY "")
set(02_RANSAC_DEPRECATED "")